# Generated by Django 5.0.7 on 2025-05-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namyangju_SP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_clicked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
